# Generated by Django 5.2.14 on 2026-09-19 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plusone", "0009_productevent_meetup_confirmed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=30)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="SafetyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("other", "Other safety concern"),
                            ("contact", "Unwanted contact details"),
                            ("harassment", "Harassment or threats"),
                            ("unsafe_meeting", "Unsafe meeting"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("handling_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="activitypost",
            name="request_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitypost",
            name="request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="request_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="request_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="chat_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="poster_last_present_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="swiper_last_present_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="waiting_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productevent",
            name="event_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productevent",
            name="match_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productevent",
            name="match_reference",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="productevent",
            name="post_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productevent",
            name="post_reference",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitypost",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="match",
            name="chat_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="close_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("declined", "Declined by participant"),
                    ("reported", "Reported safety issue"),
                    ("cancelled", "Activity cancelled"),
                    ("reset", "Identity reset"),
                    ("timeout", "Timed out"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for both participants"),
                    ("chatting", "Chatting"),
                    ("agreed", "Agreed to meet"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="chatting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productevent",
            name="name",
            field=models.CharField(
                choices=[
                    ("publish_card", "Card published"),
                    ("edit_card", "Card edited"),
                    ("match_created", "Match created"),
                    ("chat_started", "Chat started"),
                    ("both_agreed", "Both agreed"),
                    ("opener_suggested", "Openers suggested"),
                    ("opener_clicked", "Opener suggestion clicked"),
                    ("first_message_sent", "First message sent"),
                    ("message_sent", "Message sent"),
                    ("first_reply_received", "First reply received"),
                    ("agree_clicked", "Agree clicked"),
                    ("meetup_confirmed", "Meetup outcome confirmed"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["status", "waiting_expires_at"], name="match_wait_exp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activitypost",
            constraint=models.UniqueConstraint(
                fields=("user", "request_id"), name="unique_post_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                fields=("match", "sender", "request_id"), name="unique_message_request"
            ),
        ),
        migrations.AddField(
            model_name="ratelimitbucket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="safetyreport",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="plusone.match",
            ),
        ),
        migrations.AddField(
            model_name="safetyreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safety_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.UniqueConstraint(
                fields=("user", "scope", "window_start"),
                name="unique_rate_limit_window",
            ),
        ),
        migrations.AddIndex(
            model_name="safetyreport",
            index=models.Index(
                fields=["status", "created_at"], name="report_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="safetyreport",
            constraint=models.UniqueConstraint(
                fields=("match", "reporter"), name="unique_participant_report"
            ),
        ),
    ]
