# Generated by Django 5.2.14 on 2026-09-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plusone", "0011_event_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
