# Generated by Django 5.2.14 on 2026-09-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plusone", "0012_retired_identity_fence"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratelimitbucket",
            name="request_keys",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
