# Generated by Django 5.2.14 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plusone", "0013_idempotent_rate_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitypost",
            name="expected_end_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
