# Generated by Django 5.2.14 on 2026-10-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_original_arrangements(apps, schema_editor):
    Match = apps.get_model("plusone", "Match")
    for match in Match.objects.using(schema_editor.connection.alias).select_related("post__location").iterator(chunk_size=500):
        # Copy what old pages actually displayed. Do not fabricate confirmation
        # times, end times, presence, or product events for historical users.
        Match.objects.using(schema_editor.connection.alias).filter(pk=match.pk).update(
            meeting_point=match.post.location.name,
            plan_meeting_at=match.post.start_time,
            plan_expected_end_at=match.post.expected_end_time,
            plan_legacy=True,
            poster_agreed_revision=1 if match.poster_agreed else None,
            swiper_agreed_revision=1 if match.swiper_agreed else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plusone', '0014_activitypost_expected_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='match',
            name='meetup_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='meetup_cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_meetups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='plan_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='plan_expected_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='plan_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='plan_meeting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='plan_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_agreed_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_arrival_status',
            field=models.CharField(choices=[('pending', 'Not reported'), ('arrived', 'Arrived (self-reported)'), ('delayed', 'Running late (self-reported)')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_delay_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_meetup_outcome',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='poster_outcome_reason',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='swiper_agreed_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='swiper_arrival_status',
            field=models.CharField(choices=[('pending', 'Not reported'), ('arrived', 'Arrived (self-reported)'), ('delayed', 'Running late (self-reported)')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='swiper_delay_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='swiper_meetup_outcome',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='swiper_outcome_reason',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activitypost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('paused', 'Recruiting paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='name',
            field=models.CharField(choices=[('publish_card', 'Card published'), ('edit_card', 'Card edited'), ('match_created', 'Match created'), ('chat_started', 'Chat started'), ('both_agreed', 'Both agreed'), ('opener_suggested', 'Openers suggested'), ('opener_clicked', 'Opener suggestion clicked'), ('first_message_sent', 'First message sent'), ('message_sent', 'Message sent'), ('first_reply_received', 'First reply received'), ('agree_clicked', 'Agree clicked'), ('meetup_confirmed', 'Meetup outcome confirmed'), ('plan_updated', 'Meetup plan updated'), ('meetup_status_updated', 'Meetup status self-reported'), ('meetup_cancelled', 'Meetup cancelled'), ('meetup_outcome', 'Meetup outcome self-reported')], max_length=40),
        ),
        migrations.CreateModel(
            name='MeetupAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_actions', to='plusone.match')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'actor', 'request_id'), name='unique_meetup_action_request')],
            },
        ),
        migrations.RunPython(preserve_original_arrangements, migrations.RunPython.noop),
    ]
