# Generated by Django 5.2.14 on 2026-10-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plusone', '0015_versioned_meetup_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('declined', 'Declined by participant'), ('reported', 'Reported safety issue'), ('cancelled', 'Activity cancelled'), ('reset', 'Identity reset'), ('blocked', 'Blocked by participant'), ('timeout', 'Timed out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='name',
            field=models.CharField(choices=[('publish_card', 'Card published'), ('edit_card', 'Card edited'), ('match_created', 'Match created'), ('chat_started', 'Chat started'), ('both_agreed', 'Both agreed'), ('opener_suggested', 'Openers suggested'), ('opener_clicked', 'Opener suggestion clicked'), ('first_message_sent', 'First message sent'), ('message_sent', 'Message sent'), ('first_reply_received', 'First reply received'), ('agree_clicked', 'Agree clicked'), ('meetup_confirmed', 'Meetup outcome confirmed'), ('plan_updated', 'Meetup plan updated'), ('meetup_status_updated', 'Meetup status self-reported'), ('meetup_cancelled', 'Meetup cancelled'), ('meetup_outcome', 'Meetup outcome self-reported'), ('discover_visited', 'Discover visited'), ('discover_empty', 'Discover empty'), ('card_impression', 'Card shown'), ('create_started', 'Create started'), ('interested_result', 'Interest result'), ('wait_closed', 'Waiting closed'), ('maintenance_completed', 'Maintenance completed')], max_length=40),
        ),
        migrations.CreateModel(
            name='BrowserBudgetBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_key', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=24)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('request_keys', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('browser_key', 'scope', 'window_start'), name='unique_browser_budget_window')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048)),
                ('endpoint_digest', models.CharField(max_length=64, unique=True)),
                ('p256dh', models.CharField(max_length=256)),
                ('auth', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('other', 'Other safety concern'), ('contact', 'Unwanted contact details'), ('harassment', 'Harassment or threats'), ('unsafe_meeting', 'Unsafe meeting')], default='other', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('handling_notes', models.TextField(blank=True)),
                ('title_snapshot', models.CharField(blank=True, max_length=120)),
                ('description_snapshot', models.TextField(blank=True, max_length=2000)),
                ('location_snapshot', models.CharField(blank=True, max_length=200)),
                ('start_time_snapshot', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time_snapshot', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to='plusone.activitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='activity_report_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'reporter'), name='unique_activity_report')],
            },
        ),
        migrations.CreateModel(
            name='PresenceLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('visible', models.BooleanField(default=False)),
                ('last_visible_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_leases', to='plusone.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'user', 'tab_id'), name='unique_presence_tab')],
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=32)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='plusone.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'notification_key'), name='unique_push_delivery')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'target'), name='unique_user_block')],
            },
        ),
    ]
